## Pre-commit setup

ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: Running isort in all files.

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Running black in all files.

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        name: Check if python files are valid syntax for the ast parser
      - id: check-case-conflict
        name: Check for case conflict on file names for case insensitive systems.
      - id: check-merge-conflict
        name: Check for merge conflict syntax.
      - id: check-toml
        name: Check TOML files for valid syntax.
      - id: check-yaml
        name: Check YAML files for valid syntax.
      - id: debug-statements
        name: Check for debug statements.

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Remove unused imports with autoflake.
        args: ["--in-place", "--remove-all-unused-imports"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Running prettier in non-python files.
        types_or: [markdown, yaml, css, json, javascript]
