# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test application

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.py"
      - "*.yml"
  pull_request:
    branches:
      - main
    paths:
      - "*.py"
      - "*.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U poetry
          poetry install --with dev

      - name: Test with pytest
        run: tox
